public enum CharacterModificationEnum
{
  CURRENT_HEALTH,
  MAX_HEALTH,
  CURRENT_ENERGY,
  MAX_ENERGY,
  ARMOR,
  HUNGER,
  THIRST,
  HEAT_RESISTANCE,
  COLD_RESISTANCE,
  POISON_RESISTANCE,
  SHOCK_RESISTANCE,
  IMPACT_RESISTANCE,
  PIERCING_RESISTANCE
}